In [1]:
import pandas as pd

In [ ]:
"""
Files :
    
    sample csv file - https://github.com/codeforamerica/ohana-api/tree/master/data/sample-csv
    Titanic - https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv
    excel file - https://github.com/finbourne/sample-excel
"""

In [3]:
ls

LICENSE       customers.csv    help.txt    player-data.csv
Pandas.ipynb  data/            notebooks/  products.csv
README.md     dataFrame.ipynb  people.csv  requirements.txt

In [4]:
# pd.read_csv('locations.csv')
pd.read_csv('products.csv')

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Thermostat Drone Heater,Consumer approach woman us those star.,Bradford-Yu,Kitchen Appliances,74,USD,139,8619793560985,Orchid,Medium,backorder,38
1,2,Ultra Speaker Iron Grill Advanced One,Point suggest easy money operation could white.,Douglas Group,Fitness Equipment,510,USD,351,3057216124300,MediumSeaGreen,Small,backorder,27
2,3,Watch Headphones Kettle,Reach husband education.,Landry-Austin,Beauty & Personal Care,254,USD,409,9825254410556,Lavender,XXL,pre_order,2
3,4,Portable Toaster Clock Monitor Silent,Always choose school poor table main.,"Odom, Norton and Foster",Makeup,69,USD,119,9490814777808,Pink,XL,in_stock,94
4,5,Pro Toaster Oven,Worry put discuss easy back too career.,"Fowler, Mendoza and Mcdaniel",Automotive,525,USD,727,4726650403799,LightCoral,XL,in_stock,95
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Silent Router Phone Portable Automatic,Piece the fight near never once bank.,Huffman Group,Toys & Games,903,USD,737,8227581307423,MediumAquaMarine,XL,limited_stock,33
996,997,Digital Treadmill Clean Go,Apply drive outside reach apply.,Woodward Group,Toys & Games,8,USD,330,522633507294,PaleVioletRed,Medium,out_of_stock,9
997,998,Wireless Vacuum Shaver,Line cup course student each about.,Ramos-Cardenas,Beauty & Personal Care,615,USD,630,1892829625606,PaleVioletRed,Extra Large,pre_order,4
998,999,Portable Cooker Brush 360 Digital Mini,History feel worry painting only power bad.,Hooper-Bender,Men's Clothing,811,USD,566,1683591150065,LightGreen,S,in_stock,65
999,1000,Smart Watch Edge Digital Sense,Pay image either rest.,Campos Inc,Kitchen Appliances,867,USD,769,8697154897673,Gainsboro,50x70 cm,limited_stock,10

In [5]:
ds=pd.read_csv(r'products.csv')
ds["Price"] # this will give only price column

0       74
1      510
2      254
3       69
4      525
      ...
995    903
996      8
997    615
998    811
999    867
Name: Price, Length: 1000, dtype: int64

In [ ]:
ds(20) #if the column name is 20 you can use it like this

In [ ]:
pd.read_csv(r'products.csv', header=None)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
1,1,Thermostat Drone Heater,Consumer approach woman us those star.,Bradford-Yu,Kitchen Appliances,74,USD,139,8619793560985,Orchid,Medium,backorder,38
2,2,Ultra Speaker Iron Grill Advanced One,Point suggest easy money operation could white.,Douglas Group,Fitness Equipment,510,USD,351,3057216124300,MediumSeaGreen,Small,backorder,27
3,3,Watch Headphones Kettle,Reach husband education.,Landry-Austin,Beauty & Personal Care,254,USD,409,9825254410556,Lavender,XXL,pre_order,2
4,4,Portable Toaster Clock Monitor Silent,Always choose school poor table main.,"Odom, Norton and Foster",Makeup,69,USD,119,9490814777808,Pink,XL,in_stock,94
...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,996,Silent Router Phone Portable Automatic,Piece the fight near never once bank.,Huffman Group,Toys & Games,903,USD,737,8227581307423,MediumAquaMarine,XL,limited_stock,33
997,997,Digital Treadmill Clean Go,Apply drive outside reach apply.,Woodward Group,Toys & Games,8,USD,330,0522633507294,PaleVioletRed,Medium,out_of_stock,9
998,998,Wireless Vacuum Shaver,Line cup course student each about.,Ramos-Cardenas,Beauty & Personal Care,615,USD,630,1892829625606,PaleVioletRed,Extra Large,pre_order,4
999,999,Portable Cooker Brush 360 Digital Mini,History feel worry painting only power bad.,Hooper-Bender,Men's Clothing,811,USD,566,1683591150065,LightGreen,S,in_stock,65
1000,1000,Smart Watch Edge Digital Sense,Pay image either rest.,Campos Inc,Kitchen Appliances,867,USD,769,8697154897673,Gainsboro,50x70 cm,limited_stock,10

In [3]:
pd.read_csv('people.csv')

    year  population
0   2000       12400
1   2001       12800
2   2002       13800
3   2003       13600
4   2004       14200
5   2005       15600
6   2006       17600
7   2007       19200
8   2008       20300
9   2009       20800
10  2010       21200
11  2011       22400
12  2012       23400
13  2013       24500
14  2014       25800
15  2015       26100
16  2016       28300
17  2017       29600
18  2018       32100
19  2019       32500
20  2020       33200
21  2021       33800

In [5]:
df = pd.read_csv('people.csv')

In [6]:
a = 1

In [7]:
type(a)

int

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
ls

LICENSE       README.md  demo.ipynb  notebooks/  products.csv
Pandas.ipynb  data/      help.txt    people.csv  requirements.txt

In [10]:
pd.read_csv('people.csv',header=None)

       0           1
0   year  population
1   2000       12400
2   2001       12800
3   2002       13800
4   2003       13600
5   2004       14200
6   2005       15600
7   2006       17600
8   2007       19200
9   2008       20300
10  2009       20800
11  2010       21200
12  2011       22400
13  2012       23400
14  2013       24500
15  2014       25800
16  2015       26100
17  2016       28300
18  2017       29600
19  2018       32100
20  2019       32500
21  2020       33200
22  2021       33800

In [12]:
pd.read_csv('people.csv' ,names=["1st-Row" , "2nd-row"] )

   1st-Row     2nd-row
0     year  population
1     2000       12400
2     2001       12800
3     2002       13800
4     2003       13600
5     2004       14200
6     2005       15600
7     2006       17600
8     2007       19200
9     2008       20300
10    2009       20800
11    2010       21200
12    2011       22400
13    2012       23400
14    2013       24500
15    2014       25800
16    2015       26100
17    2016       28300
18    2017       29600
19    2018       32100
20    2019       32500
21    2020       33200
22    2021       33800

In [29]:
df=pd.read_csv('customers.csv')
# df.drop(['First Name','Country','Company'],axis=1)
df.pop('First Name')
df.pop('Country')
df.pop('Company')

0                     Rasmussen Group
1                         Vega-Gentry
2                       Murillo-Perry
3     Dominguez, Mcmillan and Donovan
4            Martin, Lang and Andrade
                   ...
95                          Carey LLC
96              Ware, Burns and Oneal
97                      Schmitt-Jones
98                 Fitzgerald-Harrell
99                 Le, Nash and Cross
Name: Company, Length: 100, dtype: object

In [ ]:
df = pd.read_csv('sample_test.csv',sep='|')

In [ ]:
df

       name                 emailid    address  pin code         sirname
0  sudhanshu  SSKUMAR9876@GMAIL.COM  Bengalore     560085          kumar
1     krish         krish@gmail.com  bengalore     560085           naik
2    ineuron     ineuron@ineuron.ai  Bengalore     560085  intelligence
3     pandas      pandas@ineuron.ai    chennai   25845121       tutorial

In [ ]:
pd.read_csv('sample_test.csv',sep='|' , skiprows=[1,3])

    name             emailid    address  pin code    sirname
0  krish     krish@gmail.com  bengalore     560085      naik
1  pandas  pandas@ineuron.ai    chennai   25845121  tutorial

In [ ]:
df1 = pd.read_csv('sample_test.csv',sep='|' , skiprows=[1,3])

In [ ]:
df1

    name             emailid    address  pin code    sirname
0  krish     krish@gmail.com  bengalore     560085      naik
1  pandas  pandas@ineuron.ai    chennai   25845121  tutorial

In [ ]:
df = pd.read_csv('services.csv')

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [ ]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [ ]:
df.head(2)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN

In [ ]:
df.tail(3)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [ ]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [ ]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [ ]:
df

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,None,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN
5,6,6,NaN,NaN,NaN,Walk in or apply by phone for membership appli...,Any age,A multipurpose center offering a wide variety ...,None,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, In-Home Su...",NaN,Little House Recreational Activities,NaN,San Mateo County,active,No wait.,NaN,NaN
6,7,7,NaN,NaN,NaN,"Apply by phone or be referred by a doctor, soc...","Older adults who have memory or sensory loss, ...",Rosener House is a day center for older adults...,Age 18 or over,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Adult Day ...",NaN,Rosener House Adult Day Services,NaN,"Belmont, Burlingame, East Palo Alto",active,No wait.,NaN,NaN
7,8,8,NaN,NaN,NaN,Apply by phone.,"Senior citizens age 60 or over, disabled indiv...",Delivers a hot meal to the home of persons age...,Homebound person unable to cook or shop,NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Meals on Wheels - South County,NaN,"Belmont, East Palo Alto",active,No wait.,NaN,NaN
8,9,9,NaN,NaN,NaN,Walk in. Proof of residency in California requ...,"Ethnic minorities, especially Spanish speaking","Provides general reading material, including b...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Fair Oaks Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
9,10,10,NaN,NaN,NaN,Walk in. Proof of California residency to rece...,NaN,"Provides general reading and media materials, ...",Resident of California to obtain a card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Main Library,NaN,San Mateo County,active,No wait.,NaN,NaN
10,11,11,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library car...,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Schaberg Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
11,12,12,NaN,NaN,NaN,"Walk in or apply by phone, email or webpage re...","Adults, parents, children in 1st-12th grades i...",Offers an intergenerational literacy program f...,English-speaking adult reading at or below 7th...,NaN,...,NaN,"EDUCATION SERVICES, Adult, Alternative, Litera...",NaN,Project Read,NaN,Daly City,active,Depends on availability of tutors for small gr...,NaN,NaN
12,13,13,NaN,NaN,NaN,Walk in. Proof of California residency require...,NaN,"Provides general reading materials, including ...",Resident of California to obtain a library card,NaN,...,NaN,"EDUCATION SERVICES, Library, Libraries, Public...",NaN,Redwood Shores Branch,NaN,San Mateo County,active,No wait.,NaN,NaN
13,14,14,NaN,NaN,NaN,Call for appointment. Referral from human serv...,Individuals or families with low or no income ...,"Provides food, clothing, bus tokens and shelte...",None for most services. For emergency assistan...,NaN,...,NaN,"COMMUNITY SERVICES, Interpretation/Translation...",NaN,Redwood City Corps,NaN,"Belmont, Burlingame, East Palo Alto",active,Up to 20 minutes.,NaN,NaN
14,15,15,NaN,NaN,NaN,Walk in or through other agency referral.,Adult alcoholic/drug addictive men and women w...,Provides a long-term (6-12 month) residential ...,"Age 21-60, detoxed, physically able and willin...",NaN,...,NaN,"ALCOHOLISM SERVICES, Residential Care, DRUG AB...",NaN,Adult Rehabilitation Center,NaN,"Alameda County, San Mateo County",active,Varies according to available beds for men and...,NaN,NaN
15,16,16,NaN,NaN,NaN,"Walk in. Written application, identification r...",NaN,Provides emergency assistance including food a...,None for emergency assistance,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,Sunnyvale Corps,NaN,NaN,active,No wait.,NaN,NaN
16,17,17,NaN,NaN,NaN,Call for information.,NaN,"Provides emergency food, clothing and furnitur...",Low-income families,NaN,...,NaN,"COMMODITY SERVICES, Clothing/Personal Items, C...",NaN,South San Francisco Citadel Corps,NaN,"Colma, Daly City, South San Francisco",active,NaN,NaN,NaN
17,18,18,NaN,NaN,NaN,Call for screening appointment. Medical visits...,NaN,"By appointment only, Project Smile provides a ...",Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,Project Smile,NaN,East Palo Alto,active,Varies.,NaN,NaN
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,None,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,None,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [ ]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [ ]:
a = df["name"]

In [ ]:
type(a)

pandas.core.series.Series

In [ ]:
df1 = df[["name" ,'location_id','id' ]]

In [ ]:
type(df1)

pandas.core.frame.DataFrame

In [ ]:
type(df[['name']])

pandas.core.frame.DataFrame

In [ ]:
ls

 Volume in drive C has no label.
 Volume Serial Number is FA55-E833

 Directory of C:\Users\win10\jupyter\Complete Python Module-20210227T092441Z-001\Complete Python Module\16-17. Pandas-Numpy

02/26/2022  01:00 PM    <DIR>          .
02/26/2022  01:00 PM    <DIR>          ..
02/26/2022  11:49 AM    <DIR>          .ipynb_checkpoints
07/07/2021  08:04 PM           107,005 16.1 Pandas file read and write operation.ipynb
06/01/2021  06:38 AM           138,431 16.2 Pandas data manipulation .ipynb
06/01/2021  06:38 AM           105,034 16.3 Pandas data manipulation_continue .ipynb
07/07/2021  08:04 PM            94,904 17. Numpy in details.ipynb
02/26/2022  12:05 PM             1,173 addresses.csv
02/26/2022  12:05 PM             1,589 contacts.csv
04/11/2021  06:07 AM    <DIR>          example_files
02/26/2022  12:05 PM               277 holiday_schedules.csv
02/26/2022  12:05 PM            18,015 locations.csv
02/26/2022  01:00 PM           161,651 LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xlsx
02/26/2022  01:00 PM           161,410 LUSID Excel - Maintain a product in multiple currencies and share classes.xlsx
02/26/2022  01:00 PM            71,993 LUSID Excel - Manage Orders.xlsx
02/26/2022  01:00 PM           137,753 LUSID Excel - Manage your investment strategies.xlsx
02/26/2022  01:00 PM           184,013 LUSID Excel - Setting up your IBOR.xlsx
02/26/2022  01:00 PM           136,632 LUSID Excel - Setting up your market data.xlsx
02/26/2022  12:05 PM             1,610 mail_addresses.csv
08/07/2020  11:06 PM                 0 my_database4.db
08/07/2020  11:07 PM             8,192 my_database5.db
08/08/2020  03:48 AM           189,104 mydata.h5
08/07/2020  11:06 PM             8,192 mydata2.sqlite
11/06/2021  09:38 PM            39,413 Numpy.ipynb
02/26/2022  12:05 PM             2,281 organizations.csv
10/10/2021  10:11 PM           263,960 pandas data manupulation.ipynb
02/26/2022  12:54 PM           226,444 Pandas.ipynb
02/26/2022  12:05 PM             2,092 phones.csv
02/26/2022  12:05 PM                60 programs.csv
02/26/2022  12:05 PM               350 regular_schedules.csv
02/26/2022  12:31 PM               254 sample_test.csv
02/26/2022  12:05 PM            19,128 services.csv
02/26/2022  12:17 PM            14,578 taxonomy.csv
11/06/2021  10:19 PM             5,122 Untitled1.ipynb
              30 File(s)      2,100,660 bytes
               4 Dir(s)  471,003,660,288 bytes free

In [ ]:
pd.read_excel('LUSID Excel - Manage Orders.xlsx',sheet_name = "Allocations")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,NaN,This sheet allows you to manage Allocations:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1. ListAllocations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2. GetAllocation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,3. UpsertAllocations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,NaN,Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,MyAllocation001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,NaN,MyAllocation002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df = pd.read_excel('LUSID Excel - Manage Orders.xlsx')

In [ ]:
df.keys()

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24'],
      dtype='object')

In [ ]:
df = pd.ExcelFile('LUSID Excel - Manage Orders.xlsx')

In [ ]:
df.sheet_names

['Orders', 'Allocations', 'Placements', 'Blocks']

In [ ]:
for i in df.sheet_names:
    pd.read_excel('LUSID Excel - Manage Orders.xlsx' , sheet_name=i)

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/codeforamerica/ohana-api/master/data/sample-csv/phones.csv')

,id,contact_id,location_id,organization_id,service_id,country_prefix,department,extension,number,number_type,vanity_number
0,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,650 780-7525,voice,NaN
1,2,NaN,1.0,NaN,NaN,NaN,NaN,NaN,650 701-0856,fax,NaN
2,3,NaN,2.0,NaN,NaN,NaN,NaN,4385.0,650 403-4300,voice,NaN
3,4,NaN,2.0,NaN,NaN,NaN,NaN,NaN,650 403-4302,fax,NaN
4,5,NaN,3.0,NaN,NaN,NaN,English,NaN,650 403-4300,voice,NaN
5,6,NaN,3.0,NaN,NaN,NaN,NaN,NaN,650 403-4303,fax,NaN
6,7,NaN,4.0,NaN,NaN,NaN,NaN,4500.0,650 403-4300,voice,NaN
7,8,NaN,4.0,NaN,NaN,NaN,NaN,NaN,650 403-4303,fax,NaN
8,9,NaN,5.0,NaN,NaN,NaN,NaN,4100.0,650 403-4300,voice,NaN
9,10,NaN,5.0,NaN,NaN,NaN,NaN,NaN,650 403-4303,fax,NaN
10,11,NaN,6.0,NaN,NaN,NaN,NaN,NaN,650 326-2025,voice,NaN
11,12,NaN,6.0,NaN,NaN,NaN,NaN,NaN,650 326-9547,fax,NaN
12,13,NaN,7.0,NaN,NaN,NaN,NaN,NaN,650 322-0126,voice,NaN
13,14,NaN,7.0,NaN,NaN,NaN,NaN,NaN,650 322-4067,fax,NaN
14,15,NaN,8.0,NaN,NaN,NaN,NaN,NaN,650 323-2022,voice,NaN
15,16,NaN,8.0,NaN,NaN,NaN,NaN,NaN,650 326-9547,fax,NaN
16,17,NaN,9.0,NaN,NaN,NaN,NaN,NaN,650 780-7261,voice,NaN
17,18,NaN,9.0,NaN,NaN,NaN,NaN,NaN,650 569-3371,fax,NaN
18,19,NaN,10.0,NaN,NaN,NaN,Circulation,NaN,650 780-7018,voice,NaN
19,20,NaN,10.0,NaN,NaN,NaN,NaN,NaN,650 780-7069,fax,NaN
20,21,NaN,11.0,NaN,NaN,NaN,NaN,NaN,650 780-7010,voice,NaN
21,23,NaN,12.0,NaN,NaN,NaN,NaN,NaN,650 780-7077,voice,NaN
22,24,NaN,12.0,NaN,NaN,NaN,NaN,NaN,650 780-7004,fax,NaN
23,25,NaN,13.0,NaN,NaN,NaN,NaN,NaN,650 780-5740,voice,NaN
24,26,NaN,14.0,NaN,NaN,NaN,NaN,NaN,650 368-4643,voice,NaN
25,27,NaN,14.0,NaN,NaN,NaN,NaN,NaN,650 364-1712,fax,NaN
26,28,NaN,15.0,NaN,NaN,NaN,NaN,NaN,415 643-8000,voice,NaN
27,29,NaN,15.0,NaN,NaN,NaN,NaN,NaN,415 285-1391,fax,NaN
28,30,NaN,16.0,NaN,NaN,NaN,NaN,NaN,408 720-0420,voice,NaN
29,31,NaN,16.0,NaN,NaN,NaN,NaN,NaN,408 720-8075,fax,NaN
30,32,NaN,17.0,NaN,NaN,NaN,NaN,NaN,650 266-4591,voice,NaN
31,33,NaN,17.0,NaN,NaN,NaN,NaN,NaN,650 266-2594,fax,NaN
32,34,NaN,17.0,NaN,NaN,NaN,NaN,NaN,650 266-4594,fax,NaN
33,35,NaN,18.0,NaN,NaN,NaN,NaN,NaN,650 839-1447,voice,NaN
34,36,NaN,18.0,NaN,NaN,NaN,NaN,NaN,650 839-1457,fax,NaN
35,37,NaN,19.0,NaN,NaN,NaN,NaN,NaN,650 578-0400,voice,NaN
36,38,NaN,19.0,NaN,NaN,NaN,NaN,NaN,650 578-0440,fax,NaN
37,39,NaN,21.0,NaN,NaN,NaN,CalFresh,1223.0,7035551212,voice,703-555-ABCD
38,40,NaN,21.0,NaN,NaN,NaN,CalFresh,NaN,2025551212,fax,NaN
39,41,29.0,NaN,NaN,NaN,1.0,Referrals,1200.0,123-456-7890,voice,NaN
40,42,29.0,NaN,NaN,NaN,1.0,Referrals,NaN,202-555-1212,fax,NaN
41,43,NaN,22.0,NaN,NaN,NaN,Information,123.0,650 372-6200,voice,222-555-INFO
42,44,NaN,22.0,NaN,NaN,NaN,Reservations,NaN,650 627-8244,fax,NaN
43,45,NaN,22.0,NaN,NaN,NaN,Hotline,NaN,800 372-6200,hotline,NaN
44,46,NaN,22.0,NaN,NaN,NaN,Rental Assistance,202.0,650 372-6200,tty,NaN
45,52,36.0,NaN,NaN,NaN,NaN,CalFresh Applications,123.0,703-555-1212,voice,NaN
46,53,NaN,NaN,8.0,NaN,NaN,Operations,101.0,123-456-7890,voice,NaN
47,54,32.0,NaN,NaN,NaN,NaN,Operations,NaN,703-444-1234,fax,NaN
48,55,32.0,NaN,NaN,NaN,NaN,Operations,101.0,650-555-1212,voice,NaN
49,56,NaN,11.0,NaN,NaN,NaN,NaN,NaN,650 365-3738,fax,NaN
50,57,NaN,NaN,NaN,22.0,NaN,Passport Photos,123.0,123-456-7890,voice,NaN
51,58,NaN,NaN,NaN,22.0,NaN,Passport Photos Fax,NaN,789-456-1230,fax,NaN
52,59,NaN,NaN,NaN,22.0,NaN,Passport Help via SMS,NaN,650-222-5555,sms,NaN
53,60,29.0,NaN,NaN,NaN,NaN,NaN,NaN,650-555-1212,sms,NaN

In [30]:
pd.read_csv('player-data.csv')

,player_id,version,name,full_name,description,image,height_cm,weight_kg,dob,positions,...,composure,defensive_awareness,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes,play_styles
0,239085,2024-03-27,Erling Braut Håland -,Erling Braut Håland,"Erling Haaland (Erling Braut Håland, born 21 J...",https://cdn.sofifa.net/players/239/085/24_120.png,195,94,2000-07-21,ST,...,87,38,47,29,7,14,13,11,7,"Acrobatic +,Power Header,Quick Step"
1,231747,2024-03-27,Kylian Mbappé Lottin -,Kylian Mbappé Lottin,"Kylian Mbappé (Kylian Mbappé Lottin, born 20 D...",https://cdn.sofifa.net/players/231/747/24_120.png,182,75,1998-12-20,"ST,LW",...,88,26,34,32,13,5,7,11,6,"Quick Step +,Finesse Shot,Rapid,Flair,Trivela,..."
2,192985,2024-03-27,Kevin De Bruyne -,Kevin De Bruyne,Kevin De Bruyne (born 28 June 1991) is a Belgi...,https://cdn.sofifa.net/players/192/985/24_120.png,181,75,1991-06-28,"CM,CAM",...,88,66,70,53,15,13,5,10,13,"Incisive Pass +,Dead Ball,Pinged Pass,Long Bal..."
3,231866,2024-03-27,Rodri -,Rodrigo Hernández Cascante,Rodri (born 22 June 1996) is a Spanish footbal...,https://cdn.sofifa.net/players/231/866/24_120.png,191,82,1996-06-22,"CDM,CM",...,87,92,87,78,10,10,7,14,8,"Power Shot +,Long Ball Pass,Bruiser,Aerial,Lon..."
4,202126,2024-03-27,Harry Edward Kane -,Harry Edward Kane,"Harry Kane (Harry Edward Kane, born 28 July 19...",https://cdn.sofifa.net/players/202/126/24_120.png,188,85,1993-07-28,ST,...,92,46,46,38,8,10,11,14,11,"Incisive Pass +,Long Ball Pass,First Touch,Tri..."
5,192119,2024-03-27,Thibaut Nicolas Marc Courtois -,Thibaut Nicolas Marc Courtois,Thibaut Courtois (Thibaut Nicolas Marc Courtoi...,https://cdn.sofifa.net/players/192/119/24_120.png,200,96,1992-05-11,GK,...,66,20,18,16,85,89,76,90,93,"Far Throw,Cross Claimer"
6,188545,2024-03-27,Robert Lewandowski -,Robert Lewandowski,Robert Lewandowski (born 21 August 1988) is a ...,https://cdn.sofifa.net/players/188/545/24_120.png,185,81,1988-08-21,ST,...,88,35,42,19,15,6,12,8,10,"Power Header +,Finesse Shot,Chip Shot,Power Sh..."
7,158023,2024-03-27,Lionel Andrés Messi Cuccitini -,Lionel Andrés Messi Cuccitini,"Lionel Messi (Lionel Andrés Messi Cuccitini, b...",https://cdn.sofifa.net/players/158/023/24_120.png,169,67,1987-06-24,"CF,CAM",...,96,20,35,24,6,11,15,14,8,"Technical +,Finesse Shot,Dead Ball,Incisive Pa..."
8,239818,2024-03-27,Rúben Dias -,Rúben dos Santos Gato Alves Dias,"Rúben Dias (Rúben dos Santos Gato Alves Dias, ...",https://cdn.sofifa.net/players/239/818/24_120.png,187,82,1997-05-14,CB,...,81,91,91,87,7,8,13,7,12,"Bruiser +,Power Header,Block,Leadership"
9,238794,2024-03-27,Vini Jr. -,Vinicius José Paixão de Oliveira Junior,Vini Jr. (Vinicius José Paixão de Oliveira Jun...,https://cdn.sofifa.net/players/238/794/24_120.png,176,73,2000-07-12,"LW,ST",...,79,32,25,18,5,7,7,7,10,"Quick Step +,Finesse Shot,Chip Shot,Rapid,Flai..."
10,212831,2024-03-27,Alisson -,Alisson Ramsés Becker,"Alisson (Alisson Ramsés Becker, born 2 October...",https://cdn.sofifa.net/players/212/831/24_120.png,193,91,1992-10-02,GK,...,66,15,19,16,86,85,85,90,89,"Far Throw,Cross Claimer,Rush Out"
11,209331,2024-03-27,Mohamed Salah Hamed Ghaly -,Mohamed Salah Hamed Ghaly محمد صلاح,"Mohamed Salah (Mohamed Salah Hamed Ghaly, born...",https://cdn.sofifa.net/players/209/331/24_120.png,175,72,1992-06-15,RW,...,90,38,43,41,14,14,9,11,14,"Finesse Shot +,Chip Shot,Rapid,Trivela"
12,203376,2024-03-27,Virgil van Dijk -,Virgil van Dijk,Virgil van Dijk (born 8 July 1991) is a Dutch ...,https://cdn.sofifa.net/players/203/376/24_120.png,193,92,1991-07-08,CB,...,89,90,91,86,13,10,13,11,11,"Aerial +,Power Header,Long Ball Pass,Jockey,Bl..."
13,192448,2024-03-27,Marc-André ter Stegen -,Marc-André ter Stegen,Marc-André ter Stegen (born 30 April 1992) is ...,https://cdn.sofifa.net/players/192/448/24_120.png,187,85,1992-04-30,GK,...,70,25,13,10,86,85,89,86,91,"Footwork,Cross Claimer,Rush Out"
14,190871,2024-03-27,Neymar Jr -,Neymar da Silva Santos Júnior,"Neymar Jr (Neymar da Silva Santos Júnior, born...",https://cdn.sofifa.net/players/190/871/24_120.png,175,68,1992-02-05,"LW,CAM",...,93,35,32,29,9,9,15,15,11,"Trickster +,Incisive Pass,Technical,Flair,Firs..."
15,165153,2024-03-27,Karim Benzema -,Karim Benzema كريم بن زيما,Karim Benzema (born 19 December 1987) is a Fre...,https://cdn.sofifa.net/players/165/153/24_120.png,185,81,1987-12-19,"CF,ST",...,90,43,24,18,13,11,5,5,7,"First Touch +,Finesse Shot,Incisive Pass,Tiki ..."
16,252371,2024-03-27,Jude Victor William Bellingham -,Jude Victor William Bellingham,Jude Bellingham (Jude Victor William Bellingha...,https://cdn.sofifa.net/players/252/371/24_120.png,186,75,2003-06-29,"CAM,CM",...,85,77,79,77,14,11,10,5,8,"Relentless +,Intercept,Slide Tackle,Technical,..."
17,239053,2024-03-27,Federico Santiago Valverde Dipetta -,Federico Santiago Valverde Dipetta,Federico Valverde (Federico Santiago Valverde ...,https://cdn.sofifa.net/players/239/053/24_120.png,182,78,1998-07-22,"CM,RW",...,84,79,85,79,6,10,6,15,8,"Power Shot,Long Ball Pass,Rapid,Relentless,Tri..."
18,231478,2024-03-27,Lautaro Javier Martínez -,Lautaro Javier Martínez,"Lautaro Martínez (Lautaro Javier Martínez, bor...",https://cdn.sofifa.net/players/231/478/24_120.png,174,72,1997-08-22,ST,...,88,55,31,44,11,8,8,8,13,"Technical,Flair,Trivela"
19,218667,2024-03-27,Bernardo Silva -,Bernardo Mota Veiga de Carvalho e Silva,Bernardo Silva (Bernardo Mota Veiga de Carvalh...,https://cdn.sofifa.net/players/218/667/24_120.png,173,64,1994-08-10,"CM,RW",...,89,70,76,60,9,10,14,12,9,"Technical +,Tiki Taka,Flair,Relentless,Trivela..."
20,210257,2024-03-27,Ederson -,Ederson Santana de Moraes,Ederson (born 17 August 1993) is a Brazilian f...,https://cdn.sofifa.net/players/210/257/24_120.png,188,86,1993-08-17,GK,...,70,29,15,8,87,82,91,86,87,"Long Ball Pass,Cross Claimer,Rush Out"
21,200389,2024-03-27,Jan Oblak -,Jan Oblak,Jan Oblak (born 7 January 1993) is a Slovenian...,https://cdn.sofifa.net/players/200/389/24_120.png,188,87,1993-01-07,GK,...,68,27,14,18,85,90,78,86,87,"Far Throw,Cross Claimer"
22,194765,2024-03-27,Antoine Griezmann -,Antoine Griezmann,Antoine Griezmann (born 21 March 1991) is a Fr...,https://cdn.sofifa.net/players/194/765/24_120.png,176,73,1991-03-21,ST,...,89,45,63,64,14,8,14,13,14,"Finesse Shot +,Chip Shot,Incisive Pass,Technic..."
23,256630,2024-03-27,Florian Richard Wirtz -,Florian Richard Wirtz,"Florian Wirtz (Florian Richard Wirtz, born 3 M...",https://cdn.sofifa.net/players/256/630/24_120.png,177,71,2003-05-03,CAM,...,84,58,49,44,14,14,13,6,10,"Chip Shot,Incisive Pass,Technical,Flair,First ..."
24,235073,2024-03-27,Gregor Kobel -,Gregor Kobel,Gregor Kobel (born 6 December 1997) is a Swiss...,https://cdn.sofifa.net/players/235/073/24_120.png,195,88,1997-12-06,GK,...,66,15,15,15,86,84,73,86,89,"Far Throw,Footwork,Cross Claimer,Rush Out,Lead..."
25,234378,2024-03-27,Declan Rice -,Declan Rice,Declan Rice (born 14 January 1999) is a Britis...,https://cdn.sofifa.net/players/234/378/24_120.png,185,80,1999-01-14,"CDM,CM",...,83,85,86,85,8,11,14,5,9,"Long Ball Pass,Block,Intercept,Press Proven,Lo..."
26,232293,2024-03-27,Victor James Osimhen -,Victor James Osimhen,"Victor Osimhen (Victor James Osimhen, born 29 ...",https://cdn.sofifa.net/players/232/293/24_120.png,186,77,1998-12-29,ST,...,80,36,45,22,14,14,10,9,6,"Chip Shot,Power Header,Rapid,Acrobatic"
27,230621,2024-03-27,Gianluigi Donnarumma -,Gianluigi Donnarumma,Gianluigi Donnarumma (born 25 February 1999) i...,https://cdn.sofifa.net/players/230/621/24_120.png,196,90,1999-02-25,GK,...,65,20,14,16,90,81,73,83,89,"Cross Claimer,Rush Out"
28,228702,2024-03-27,Frenkie de Jong -,Frenkie de Jong,Frenkie de Jong (born 12 May 1997) is a Dutch ...,https://cdn.sofifa.net/players/228/702/24_120.png,181,74,1997-05-12,"CM,CDM",...,90,76,76,77,7,13,10,10,9,"Trivela +,Incisive Pass,Long Ball Pass,Tiki Ta..."
29,222665,2024-03-27,Martin Ødegaard -,Martin Ødegaard,Martin Ødegaard (born 17 December 1998) is a N...,https://cdn.sofifa.net/players/222/665/24_120.png,178,68,1998-12-17,"CAM,CM",...,87,67,59,57,14,15,15,8,10,"Incisive Pass +,Pinged Pass,Whipped Cross,Tech..."
30,215698,2024-03-27,Mike Peterson Maignan -,Mike Peterson Maignan,"Mike Maignan (Mike Peterson Maignan, born 3 Ju...",https://cdn.sofifa.net/players/215/698/24_120.png,191,89,1995-07-03,GK,...,68,23,16,19,85,82,87,85,89,"Far Throw,Cross Claimer,Leadership"
31,212622,2024-03-27,Joshua Walter Kimmich -,Joshua Walter Kimmich,"Joshua Kimmich (Joshua Walter Kimmich, born 8 ...",https://cdn.sofifa.net/players/212/622/24_120.png,177,75,1995-02-08,"CDM,RB,CM",...,86,81,84,78,8,15,7,15,15,"Long Ball Pass +,Whipped Cross,Press Proven,Re..."
32,212198,2024-03-27,Bruno Fernandes -,Bruno Miguel Borges Fernandes,Bruno Fernandes (born 8 September 1994) is a P...,https://cdn.sofifa.net/players/212/198/24_120.png,179,69,1994-09-08,"CM,CAM",...,79,62,71,63,12,14,15,8,14,"Pinged Pass +,Incisive Pass,Long Ball Pass,Fla..."
33,207865,2024-03-27,Marquinhos -,Marcos Aoás Corrêa,Marquinhos (born 14 May 1994) is a Brazilian f...,https://cdn.sofifa.net/players/207/865/24_120.png,183,75,1994-05-14,CB,...,86,90,89,88,6,6,12,10,13,"Intercept +,Power Header,Jockey,Anticipate,Aer..."
34,200104,2024-03-27,Heung-Min Son -,Heung-Min Son 손흥민 孙兴慜,"Heung Min Son (孙兴慜, Heung-Min Son, born 8 July...",https://cdn.sofifa.net/players/200/104/24_120.png,183,78,1992-07-08,"LW,LM,ST",...,88,47,34,33,11,13,13,6,10,"Finesse Shot +,Rapid,Quick Step,Long Shot Take..."
35,177003,2024-03-27,Luka Modrić -,Luka Modrić,Luka Modrić (born 9 September 1985) is a Croat...,https://cdn.sofifa.net/players/177/003/24_120.png,172,66,1985-09-09,"CM,CAM",...,92,70,73,72,13,9,7,14,9,"Trivela +,Incisive Pass,Long Ball Pass,Whipped..."
36,167495,2024-03-27,Manuel Peter Neuer -,Manuel Peter Neuer,"Manuel Neuer (Manuel Peter Neuer, born 27 Marc...",https://cdn.sofifa.net/players/167/495/24_120.png,193,93,1986-03-27,GK,...,70,17,10,11,84,85,90,88,84,"Pinged Pass,Far Throw,Cross Claimer,Rush Out,I..."
37,256790,2024-03-27,Jamal Musiala -,Jamal Musiala,Jamal Musiala (born 26 February 2003) is a Ger...,https://cdn.sofifa.net/players/256/790/24_120.png,184,72,2003-02-26,"CAM,LM,CM",...,84,64,63,68,6,9,8,8,11,"Technical +,Flair,First Touch,Trickster,Long S..."
38,253163,2024-03-27,Ronald Federico Araújo da Silva -,Ronald Federico Araújo da Silva,Ronald Araujo (Ronald Federico Araújo da Silva...,https://cdn.sofifa.net/players/253/163/24_120.png,188,79,1999-03-07,"CB,RB",...,76,86,86,86,11,14,9,11,8,"Block +,Power Header,Jockey,Anticipate,Slide T..."
39,251854,2024-03-27,Pedri -,Pedro González López,Pedri (born 25 November 2002) is a Spanish foo...,https://cdn.sofifa.net/players/251/854/24_120.png,174,60,2002-11-25,"CM,LW",...,87,68,77,65,12,7,11,8,8,"Tiki Taka +,Incisive Pass,Long Ball Pass,Techn..."
40,247635,2024-03-27,Khvicha Kvaratskhelia -,Khvicha Kvaratskhelia ხვიჩა კვარაცხელია,Khvicha Kvaratskhelia (born 12 February 2001) ...,https://cdn.sofifa.net/players/247/635/24_120.png,183,70,2001-02-12,"LW,RW",...,79,38,39,34,9,15,8,14,8,"Trickster +,Finesse Shot,Incisive Pass,Whipped..."
41,246669,2024-03-27,Bukayo Saka -,Bukayo Saka,Bukayo Saka (born 5 September 2001) is a Briti...,https://cdn.sofifa.net/players/246/669/24_120.png,178,65,2001-09-05,"RW,RM",...,81,60,62,60,7,8,13,9,13,"Finesse Shot,Technical,Flair"
42,241721,2024-03-27,Rafael Leão -,Rafael Alexandre da Conceição Leão,Rafael Leão (Rafael Alexandre da Conceição Leã...,https://cdn.sofifa.net/players/241/721/24_120.png,188,81,1999-06-10,"LW,CF,LM",...,83,22,24,21,10,12,15,11,9,"Rapid +,Finesse Shot,Whipped Cross,Flair,Trick..."
43,240130,2024-03-27,Éder Militão -,Éder Gabriel Militão,Éder Militão (born 18 January 1998) is a Brazi...,https://cdn.sofifa.net/players/240/130/24_120.png,186,78,1998-01-18,CB,...,74,86,87,85,11,8,15,12,15,"Power Header,Long Ball Pass,Block,Intercept,Ae..."
44,237692,2024-03-27,Philip Walter Foden -,Philip Walter Foden,"Phil Foden (Philip Walter Foden, born 28 May 2...",https://cdn.sofifa.net/players/237/692/24_120.png,171,69,2000-05-28,"LW,RW,CAM",...,86,60,59,47,8,15,6,10,13,"First Touch +,Technical,Flair"
45,232411,2024-03-27,Christopher Alan Nkunku -,Christopher Alan Nkunku,"Christopher Nkunku (Christopher Alan Nkunku, b...",https://cdn.sofifa.net/players/232/411/24_120.png,175,73,1997-11-14,"CF,CAM,ST",...,81,62,64,54,5,6,10,15,7,"Finesse Shot,Incisive Pass,Technical,Flair,Fir..."
46,231443,2024-03-27,Masour Ousmane Dembélé -,Masour Ousmane Dembélé,"Ousmane Dembélé (Masour Ousmane Dembélé, born ...",https://cdn.sofifa.net/players/231/443/24_120.png,178,67,1997-05-15,RW,...,81,42,30,33,6,6,14,10,13,"Rapid +,Flair,Trickster,Quick Step,Injury Prone"
47,231281,2024-03-27,Trent John Alexander-Arnold -,Trent John Alexander-Arnold,Trent Alexander-Arnold (Trent John Alexander-A...,https://cdn.sofifa.net/players/231/281/24_120.png,180,72,1998-10-07,RB,...,82,78,82,78,14,15,14,6,7,"Long Ball Pass +,Dead Ball,Incisive Pass,Whipp..."
48,224232,2024-03-27,Nicolò Barella -,Nicolò Barella,Nicolò Barella (born 7 February 1997) is an It...,https://cdn.sofifa.net/players/224/232/24_120.png,172,68,1997-02-07,CM,...,86,80,83,81,11,5,13,14,11,"Relentless +,Tiki Taka,Slide Tackle,Long Shot ..."
49,223848,2024-03-27,Sergej Milinković-Savić -,Sergej Milinković-Savić Сергеј Милинковић-Савић,Sergej Milinković-Savić (born 27 February 1995...,https://cdn.sofifa.net/players/223/848/24_120.png,192,95,1995-02-27,"CM,CDM",...,84,77,77,79,7,10,7,16,7,"Power Header,Incisive Pass,First Touch,Relentl..."
50,222492,2024-03-27,Leroy Aziz Sané -,Leroy Aziz Sané,"Leroy Sané (Leroy Aziz Sané, born 11 January 1...",https://cdn.sofifa.net/players/222/492/24_120.png,183,80,1996-01-11,"RM,LM",...,83,36,32,35,8,12,9,9,14,"Rapid +,Power Shot,Flair,Quick Step,Long Shot ..."
51,216267,2024-03-27,Andrew Henry Robertson -,Andrew Henry Robertson,"Andrew Robertson (Andrew Henry Robertson, born...",https://cdn.sofifa.net/players/216/267/24_120.png,178,64,1994-03-11,LB,...,83,83,83,81,11,8,10,7,14,"Relentless +,Whipped Cross,Rapid,Early Crosser..."
52,211110,2024-03-27,Paulo Bruno Exequiel Dybala -,Paulo Bruno Exequiel Dybala,"Paulo Dybala (Paulo Bruno Exequiel Dybala, bor...",https://cdn.sofifa.net/players/211/110/24_120.png,177,75,1993-11-15,"CF,CAM,ST",...,84,32,41,39,5,4,4,5,8,"Flair +,Finesse Shot,Dead Ball,Technical,First..."
53,210514,2024-03-27,João Cancelo -,João Pedro Cavaco Cancelo,João Cancelo (born 27 May 1994) is a Portugues...,https://cdn.sofifa.net/players/210/514/24_120.png,182,74,1994-05-27,"RB,LB,RM",...,85,79,83,79,6,9,15,14,14,"Whipped Cross,Block,Technical,Flair,First Touc..."
54,210035,2024-03-27,Grimaldo -,Alejandro Grimaldo García,Grimaldo (born 20 September 1995) is a Spanish...,https://cdn.sofifa.net/players/210/035/24_120.png,171,68,1995-09-20,"LWB,LM",...,83,76,78,74,7,13,10,7,13,"Whipped Cross +,Dead Ball,Anticipate,Long Shot..."
55,208128,2024-03-27,Hakan Çalhanoğlu -,Hakan Çalhanoğlu,Hakan Çalhanoğlu (born 8 February 1994) is a T...,https://cdn.sofifa.net/players/208/128/24_120.png,178,69,1994-02-08,"CM,CDM",...,85,74,74,65,9,14,11,6,10,"Long Ball Pass,Trivela,Long Shot Taker (CPU AI)"
56,204485,2024-03-27,Riyad Mahrez -,Riyad Mahrez رياض محرز,Riyad Mahrez (born 21 February 1991) is an Alg...,https://cdn.sofifa.net/players/204/485/24_120.png,179,67,1991-02-21,"RM,RW",...,81,45,34,22,15,9,13,11,6,"First Touch +,Finesse Shot,Technical,Flair,Lon..."
57,202811,2024-03-27,Damián Emiliano Martínez Romero -,Damián Emiliano Martínez Romero,Emiliano Martínez (Damián Emiliano Martínez Ro...,https://cdn.sofifa.net/players/202/811/24_120.png,195,88,1992-09-02,GK,...,62,11,20,20,84,82,83,85,85,"Far Throw,Cross Claimer,Solid Player,Team Play..."
58,200145,2024-03-27,Casemiro -,Carlos Henrique Casimiro,"Casemiro (Carlos Henrique Casimiro, born 23 Fe...",https://cdn.sofifa.net/players/200/145/24_120.png,185,84,1992-02-23,CDM,...,81,86,87,87,13,14,16,12,12,"Block +,Long Ball Pass,Slide Tackle,Long Shot ..."
59,186942,2024-03-27,İlkay Gündoğan -,İlkay Gündoğan,İlkay Gündoğan (born 24 October 1990) is a Ger...,https://cdn.sofifa.net/players/186/942/24_120.png,180,80,1990-10-24,"CM,CDM",...,87,77,75,67,11,14,5,5,13,"Incisive Pass,Press Proven,Long Shot Taker (CP..."